62: since `pip uninstall flask-httpauth` crashes with `ImportError: cannot import name 'safe_str_compare' from 'werkzeug.security'`, do `pip install flask-httpauth` + `pip freeze > requirements.txt`