70: address the following crash observed in the workflow's job called `run-tests-for-frontend`: ```     Details:
    /home/runner/work/vocab-treasury/vocab-treasury/frontend/node_modules/axios/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import axios from './lib/axios.js';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      1 | import { Dispatch } from "redux";
    > 2 | import axios from "axios";
```